// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSong(arg1) {
  return window['go']['main']['Music']['AddSong'](arg1);
}

export function DelSong(arg1) {
  return window['go']['main']['Music']['DelSong'](arg1);
}

export function GetAllSong() {
  return window['go']['main']['Music']['GetAllSong']();
}

export function IsExist(arg1) {
  return window['go']['main']['Music']['IsExist'](arg1);
}
