// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSong(arg1:main.Song):Promise<void>;

export function DelSong(arg1:string):Promise<void>;

export function GetAllSong():Promise<Array<main.Song>>;

export function IsExist(arg1:string):Promise<boolean>;
